name: Testing

defaults:
  run:
    shell: bash

on: [pull_request]
jobs:
  test:
    runs-on: ${{ matrix.os }}
    strategy:
      fail-fast: true
      matrix:
        ghc: ["8.10.4", "8.10.3"]
        os: [ubuntu-latest, macOS-latest]
        include:
          # only test supported ghc major versions
          - os: ubuntu-latest
            ghc: "8.10.4"
            test: true
          - os: windows-latest
            ghc: "8.10.4"
            test: true
          - os: windows-latest
            ghc: "8.10.2.2"
          - os: windows-latest
            ghc: "8.10.3"
          # This build get stuck frequently
          # - os: windows-latest
          #   ghc: '8.6.4'

    steps:
      # Cancel queued workflows from earlier commits in this branch
      - uses: fkirc/skip-duplicate-actions@master

      - uses: actions/checkout@v2
        with:
          submodules: true
      - uses: haskell/actions/setup@v1
        with:
          ghc-version: ${{ matrix.ghc }}
          cabal-version: "3.2"

      - name: Set some Windows-specific things
        if: matrix.os == 'windows-latest'
        run: |
          echo "CABAL_STORE_DIR=$SYSTEMDRIVE\\SR" >> $GITHUB_ENV
          echo "CABAL_PKGS_DIR=~\\AppData\\cabal\\packages" >> $GITHUB_ENV
      - name: Set some Linux/macOS specific things
        if: matrix.os != 'windows-latest'
        run: |
          echo "CABAL_STORE_DIR=~/.cabal/store" >> $GITHUB_ENV
          echo "CABAL_PKGS_DIR=~/.cabal/packages" >> $GITHUB_ENV
      - name: Cache Cabal
        uses: actions/cache@v2
        env:
          cache-name: cache-cabal
        with:
          path: |
            ${{ env.CABAL_PKGS_DIR }}
            ${{ env.CABAL_STORE_DIR }}
          key: v2-${{ runner.os }}-${{ matrix.ghc }}-build-${{ hashFiles('cabal.project') }}
          restore-keys: |
            v2-${{ runner.os }}-${{ matrix.ghc }}-bench-${{ hashFiles('cabal.project') }}
            v2-${{ runner.os }}-${{ matrix.ghc }}-build-
            v2-${{ runner.os }}-${{ matrix.ghc }}
      - run: cabal update

      - name: Build
        # Retry it three times to workaround compiler segfaults in windows
        run: cabal build --enable-tests || cabal build --enable-tests || cabal build --enable-tests

      - name: Test
        if: ${{ matrix.test }}
        run: cabal test all
